# Generated by Django 5.1.4 on 2024-12-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=300)),
                ('cast', models.CharField(max_length=800)),
                ('release_year', models.IntegerField()),
                ('description', models.TextField(max_length=5000)),
                ('release_date', models.DateField()),
                ('average_rating', models.FloatField()),
            ],
        ),
    ]
